version: "3.9"
services:
  db:
    platform: linux/amd64 # configuration for M1 macs
    image: mysql
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test